### ISSUE TITLE
Attachments shows Loading...

### ISSUE THREAD

**Issue by ritaschaff** [holatuwol/liferay-zendesk-userscript#19]
1. Go to a ticket
2. Click on the Attachments link

✔️ **Expected behavior**: list of attachments are displayed.
❌ **Actual behavior**: list of attachments are not visible, the popup is stuck loading.
![image](https://github.com/user-attachments/assets/d2f8442c-ee21-4ba8-ad8d-51aafddb0a26)

**Comment by holatuwol** [comment]
Thanks for the heads up! This should be fixed by the following commit:
* https://github.com/holatuwol/liferay-zendesk-userscript/commit/f0fd8bcfe33e386389735cc8463f776b677cf48f
* https://github.com/holatuwol/liferay-faster-deploy/commit/76cc64f85c1b1217effa2061f98111125d922b5c
