### ISSUE TITLE
Permalinks disappeared

### ISSUE THREAD

**Issue by ritaschaff** [holatuwol/liferay-zendesk-userscript#20]
Hi, I’ve noticed that as some of the code breaks due to the latest Zendesk upgrades, the permalinks to Ticket messages disappeared.
The root cause is likely at this part:

```javascript
var actionsElement = comments[i].querySelector('.omnilog-header-actions');
```

Since `.omnilog-header-actions` is not found, the rest of the code cannot execute either.

**Comment by holatuwol** [comment]
Thanks for the heads up! This should be fixed by the following commit:
* https://github.com/holatuwol/liferay-zendesk-userscript/commit/b38ab4a20c262e57ccdc4c624f6cc95ec1647881
* https://github.com/holatuwol/liferay-faster-deploy/commit/17f68fb5e40bbe56a959d43f3b18c50520bc941a
