### ISSUE TITLE
Feature Request: product labels based on tags

### ISSUE THREAD

**Issue by ritaschaff** [holatuwol/liferay-zendesk-userscript#21]
Hi,

There are many tags that are highlighted already, but I think that highlighting the product will always be useful.
A lot of times a bug is related to the product - hence the offering would be set as a Quarterly Release - but it would be important to know if the customer is on Self-hosted, PaaS or SaaS (e.g. think of the hotfix release workflow).

Previously, there were tags for LXC and LXC_SM, but as far as I can see, they no longer show up. I couldn’t find them in the code either. But it’s ok, instead, it would be nice to have one of these 3: 
* Self-hosted
* SaaS
* PaaS

You may need to add a method that checks for tags starting with
`lxc_sm` → `PaaS` would be visible
`lxc` → `SaaS` would be visible
`dxp` → `Self-hosted` would be visible

Tags related to cloud:
```
lxc_sm
prd_lxc_sm
lxc_sm_services
lxc_sm_projects
lxc_sm_deployments
lxc_pro
prd_lxc_pro
lxc_sm_settings
lxc_engage
prd_lxc_engage
prd_lxc_support
lxc_sm_project_administration
lxc_support
lxc_sm_network
lxc_enterprise
```
Let me know in case you need anything else for this.

**Comment by holatuwol** [comment]
This has been added.

https://github.com/holatuwol/liferay-zendesk-userscript/commit/b94ca1cf616e944eafa215d06de051472fd5f5fa
https://github.com/holatuwol/liferay-faster-deploy/commit/4b16654afbde7aacbc93a2f9bfc5cdf8ee84a58b

**Comment by ritaschaff** [comment]
Thank you!

**Comment by ritaschaff** [comment]
This looks super amazing, thank you. 🙇‍♀️
