### ISSUE TITLE
Internal notes do not have the generated permalink

### ISSUE THREAD

**Issue by ritaschaff** [holatuwol/liferay-zendesk-userscript#22]
I’ve checked a ticket, e.g. 116127 and the internal notes did not have the permalink.
Is this intended?
![image](https://github.com/user-attachments/assets/243c761a-a173-42af-913c-1c6703473941)

**Comment by holatuwol** [comment]
Not intended, thanks for the heads up!

https://github.com/holatuwol/liferay-zendesk-userscript/commit/7c9e11c8eb4352c84d9d03a17cace97631f8ec26
https://github.com/holatuwol/liferay-faster-deploy/commit/17323e603f7414e950c559c724f3752f2ec24dd5
