### ISSUE TITLE
Label for High priority cases

### ISSUE THREAD

**Issue by ritaschaff** [holatuwol/liferay-zendesk-userscript#23]
Example: #116390

We have customers with high cases - and this should be reflected on the ticket as well, with a tag.
Can you please add a red background label with the text **Critical** or **High**?
It should be based on the Priority field's value.

Thank you.

**Comment by holatuwol** [comment]
This is done.

https://github.com/holatuwol/liferay-zendesk-userscript/commit/d600642d4b490aa6154b891cb9f907fcc0398683
https://github.com/holatuwol/liferay-faster-deploy/commit/dcd3ed2c395423ffad5141eb66bbfc3cb41ecc13

**Comment by ritaschaff** [comment]
Thank you so much!
