### ISSUE TITLE
Userscript update bug report link is incorrect

### ISSUE THREAD

**Issue by ritaschaff** [holatuwol/liferay-zendesk-userscript#24]
Apparently, you can set a separate URL for adding issues, like this:

```javascript
// @supportURL     https://github.com/holatuwol/liferay-zendesk-userscript/issues/new
``` 
I’ve tested this with TamperMonkey and it worked.
Can you please add it to line 7? Or do you prefer that we report issues and feature requests at the update URL? 

Please let me know, thanks.

**Comment by holatuwol** [comment]
Sure, this is done.

https://github.com/holatuwol/liferay-zendesk-userscript/commit/7995724fec7e6b1e8b73f60bd7a630b6efaa18c7
https://github.com/holatuwol/liferay-faster-deploy/commit/96bdf2f423b13b961a85aa53ca45759646496566
