### ISSUE TITLE
Incorrect versions under the Patcher Portal section 🤔 

### ISSUE THREAD

**Issue by ritaschaff** [holatuwol/liferay-zendesk-userscript#26]
This won’t be a clear request because I have no idea for a solution.

### Problem
I’ve noticed on [117926](https://liferay-support.zendesk.com/agent/tickets/117926) that only these versions are displayed:
![image](https://github.com/user-attachments/assets/ae7049ef-ad2f-4d54-b854-554a3d474799)
whereas if I check all the bundles belonging to that account, I can see
![image](https://github.com/user-attachments/assets/dbd7c380-d36e-42d1-abd1-77206d7819c0)

From what I’ve seen, the versions are probably displayed based on the tags. In this case, I could see that only one tag was added to the ticket - most likely a Zendesk issue.
Properly getting the correct versions are most likely not possible - but I wonder if we could somehow improve the current behavior?

My problem is that I usually click on the last available version to see the customer's hotfixes, and then I suddenly see that there are no patches at all for that version, then I have to go back, and check all the versions.

### Feature Ideas
One idea I was wondering about if we could utilize the Notes field in order to store information about the customer's versions - and that could override the default behavior, which is based on tags.

**Tags in the Notes section**
It could be something like "if the tag `7_2_eps, quarterly_release` is added to the Notes section, then that version would override the tags and would display **7.2 Builds** and **Quarterly Release Builds** instead.

**Build link based on the Offering field**
You could do a check to make sure that a link to the builds is always added based on the Offering field.
E.g. if it is set to **Quarterly Release** then a **Quarterly Release Builds** link should be displayed.

These are just some random ideas - but implementing them would spare us a couple of clicks, which is especially useful because Patcher Portal can be kinda slow....

**Comment by holatuwol** [comment]
I'll use the offering and ignore EPS tags.

https://github.com/holatuwol/liferay-zendesk-userscript/commit/a82dddcd5483c071422fd76507f7599f41409cf5
https://github.com/holatuwol/liferay-faster-deploy/commit/457c0c0ca7b85f997c00a57485fa0b390d94b023
