### ISSUE TITLE
Fast Track button - multiple random links

### ISSUE THREAD

**Issue by ritaschaff** [holatuwol/liferay-zendesk-userscript#28]
Hi, I found a weird thing on some tickets, like 117392.
Maybe because they are closed?

**Steps to reproduce**
1. Open the ticket
2. Click on the Fast Track button

✔️ **Expected behavior**: only the listed KCS articles are visible or none.
❌ **Actual behavior**: a link is repeated multiple times.
![image](https://github.com/user-attachments/assets/43324713-c729-4884-a323-8e79e956acee)

I tried to find the link or the ID in the link but could not find it in the HTML.

**Comment by ritaschaff** [comment]
Hi,

I found another example here:
![image](https://github.com/user-attachments/assets/01e16387-7ba4-40a0-8961-d319b69eafc7)

**Comment by holatuwol** [comment]
I didn't see any issues when I viewed the specific article you mentioned, but I've added code to make sure each link is only added once.

https://github.com/holatuwol/liferay-zendesk-userscript/commit/94e4d7eaf8ce94000adbdb42181839ee026b8a4f
