### ISSUE TITLE
Clicking on Attachments Directs Users Away from the Zendesk View

### ISSUE THREAD

**Issue by exela** [holatuwol/liferay-zendesk-userscript#5]
When using the script and clicking on any picture attachments (.jpg, .jpeg, .png, .gif, etc.) - the user is directed away from the Zendesk ticket.  The attachment is opened in the same window.

Opening in a modal or a new window/tab would prevent this issue.

**Comment by holatuwol** [comment]
Updated so that the links trigger a clicking on the original attachment, which should bring up the modal dialog that you'd get if you scrolled down to the post and clicked on the attachment.
