### ISSUE TITLE
Attachment zip seems to be empty lately

### ISSUE THREAD

**Issue by sorin-pop** [holatuwol/liferay-zendesk-userscript#7]
Lately I noticed that the Attachments feature does not seem to work well anymore. It generates a zip file, I can download the zip, but it is empty, there's nothing in it.

Can you check if you can reproduce this as well? (I use Chrome, if that matters)

**Comment by holatuwol** [comment]
078845b04729eecdd0f88cc9f264d1ff8ed54145
